server:
  port: 8080

oauth:
  server:
    baseUrl: http://localhost:9000

spring:
  security:
    oauth2:
      client:
        registration:
          messaging-client:
            provider: custom-provider
            clientId: messaging-client
            clientSecret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/messaging-client"
            scope: openid,profile
            client-name: Spring
        provider:
          custom-provider:
            authorization-uri: ${oauth.server.baseUrl}/oauth2/authorize
            token-uri: ${oauth.server.baseUrl}/oauth2/token
#            jwk-set-uri: ${oauth.server.baseUrl}/oauth2/jwks

#logging:
#  level:
#    org:
#      springframework:
#        web: TRACE
#        http: TRACE
#        security: TRACE